config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :pages, only: :home
  resources :habits, only: [:index, :show, :new, :create, :destroy]
  resources :trackers 

  resources :challenges, only: [:index, :show] do
    member do
      post :join
    end
  end

  get "calendar", to: "calendar#index", as: :calendar_index

  resources :calendar, only: [] do
    collection do
      get :day
    end
  end

  # Routes pour les erreurs
  # Utilisation de match pour get, post, patch, delete
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

end

app/views/shared/_achievement.html.erb
<div class="card text-white" style="background: linear-gradient(90deg, #5680E9, #8860D0);">
  <div class="card-body">
    <div class="row text-center">
      <div class="col-3">
        <svg class="mb-1" width="24" height="24" fill="none" stroke="currentColor" stroke-width="2">
          <path d="M11.562 3.266a.5.5 0 0 1 .876 0L15.39 8.87a1 1 0 0 0 1.516.294L21.183 5.5a.5.5 0 0 1 .798.519l-2.834 10.246a1 1 0 0 1-.956.734H5.81a1 1 0 0 1-.957-.734L2.02 6.02a.5.5 0 0 1 .798-.519l4.276 3.664a1 1 0 0 0 1.516-.294z"></path>
          <path d="M5 21h14"></path>
        </svg>
        <div class="fw-bold">Niveau</div>
        <div class="small">Apprenti</div>
      </div>
      <div class="col-3">
        <svg class="mb-1" width="24" height="24" fill="none" stroke="currentColor" stroke-width="2">
          <path d="M4 14a1 1 0 0 1-.78-1.63l9.9-10.2a.5.5 0 0 1 .86.46l-1.92 6.02A1 1 0 0 0 13 10h7a1 1 0 0 1 .78 1.63l-9.9 10.2a.5.5 0 0 1-.86-.46l1.92-6.02A1 1 0 0 0 11 14z"></path>
        </svg>
        <div class="fw-bold"><%= @user.xp_reward %></div>
        <div class="small">XP Total</div>
      </div>
      <div class="col-3">
        <svg xmlns="http://www.w3.org/2000/svg" class="mb-1" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-trophy h-8 w-8 mx-auto mb-2" aria-hidden="true">
          <path d="M10 14.66v1.626a2 2 0 0 1-.976 1.696A5 5 0 0 0 7 21.978"></path>
          <path d="M14 14.66v1.626a2 2 0 0 0 .976 1.696A5 5 0 0 1 17 21.978"></path>
          <path d="M18 9h1.5a1 1 0 0 0 0-5H18"></path><path d="M4 22h16"></path>
          <path d="M6 9a6 6 0 0 0 12 0V3a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1z"></path>
          <path d="M6 9H4.5a1 1 0 0 1 0-5H6"></path>
        </svg>
        <div class="fw-bold">2</div>
        <div class="small">Succès</div>
      </div>
      <div class="col-3">
        <svg xmlns="http://www.w3.org/2000/svg" class="mb-1" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-award h-8 w-8 mx-auto mb-2" aria-hidden="true">
          <path d="m15.477 12.89 1.515 8.526a.5.5 0 0 1-.81.47l-3.58-2.687a1 1 0 0 0-1.197 0l-3.586 2.686a.5.5 0 0 1-.81-.469l1.514-8.526"></path>
          <circle cx="12" cy="8" r="6"></circle></svg>
        <div class="fw-bold">3</div>
        <div class="small">Badges</div>
      </div>
    </div>
    <div class="mt-3" data-controller="xp-progress"
     data-xp-progress-progress-value="<%= @user.xp_progress_percentage(500) %>">
      <div class="d-flex justify-content-between mb-3 mt-2">
        <span>Progression</span>
        <span>  <%= @user.xp_reward %> / 500 xp</span>
      </div>
      <div class="progress-bar-container">
      <div class="progress-bar"
           style="width: 0%;"
           data-progress="<%= @user.xp_reward %>"
           data-xp-progress-target="bar">
      </div>
    </div>
    </div>
  </div>
</div>

app/views/shared/_card-content.html.erb
<div class="card d-flex justify-content-between">
  <h3 class="fw-bold"><%= habit.name %></h3>
  <% goal = Goal.find_by(habit: habit) %>
  <p>Objectif : <%= goal.value %> <%= habit.habit_type.unit %> <%= goal.translate_frequency %>.</p>
  <div class="d-flex bottom-card justify-content-start align-items-end gap-2">
    <div class="info-content col-8 bg-white rounded-5 shadow d-flex justify-content-between align-items-center gap-3 p-3">
      <i class="fa-solid fa-chart-column"></i>
      <span>
        <strong class="fs-3">
      <%# <%  last_valid_tracker = habit.trackers.where.not(value: [nil, 0]).last
      raise
        days_since = (Date.today - last_valid_tracker.date).to_i
      %>
      <%# <%= days_since %><%= habit.trackers.count %>
        </strong>
        jours consécutifs
      </span>
    </div>
    <%# Appliquer la couleur différente si tracker du jour rempli %>
  </div>
  <div class="checkbox text-end">
    <% if habit.trackers.where(date: Date.today).present? %>
      <i class="fa-regular fa-circle-check fs-1 px-2" id="check"></i>
    <% else %>
      <i class="fa-solid fa-hourglass-start fs-2 px-2" id="hourglass"></i></i>
  <% end %>
</div>
</div>

app/views/shared/_challenge.html.erb
<div class="card card-challenge justify-content-between" >
  <div class="d-flex justify-content-between">
    <h3 class="col-8 fw-bold"><%= challenge.name %></h3>
    <%= image_tag('icons/trophy-purple.png', id: "trophy-icon-purple") %>
  </div>
  <div>
    <span>Objectif : </span><%= challenge.objective %>
  </div>
  <span class="align-self-end">
  Par :
  <%= image_tag("avatars/#{challenge.creator}", class:"avatar-bordered w-8 h-8 rounded-full", alt: challenge.creator) %>
  </span>
</div>

app/views/shared/_footer.html.erb
<footer class="site-footer">
  <div class="container py-3 footer">
    <%= link_to root_path do %>
        <%= image_tag("icons/home.png", class:"footer-btn")%>
    <% end %>
    <%= link_to challenges_path do %>
        <%= image_tag("icons/trophy.png", class:"footer-btn")%>
    <% end %>
    <button class="btn btn-primary" id="btn-add" data-bs-toggle="modal" data-bs-target="#habitFormModal">
      <%= image_tag("icons/add.png", class:"add-btn")%>
    </button>
      <%= image_tag("icons/community.png", class:"community-btn")%>
    <%= link_to calendar_index_path do %>
      <%= image_tag("icons/calendar.png", class:"calendar-btn")%>
    <% end %>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="site-header">
  <div class="container py-3 header">
    <%= link_to root_path, class:"logo" do %>
      <%= image_tag("logo-habits.png", class:"img-logo")%>
      <h1 class="gradient-text text-logo" style="margin: 0;">Habits</h1>
    <% end %>
    <% if user_signed_in? %>
      <% if @user.avatar.present? %>
          <%= link_to image_tag("avatars/#{@user.avatar}", class:"avatar-bordered w-8 h-8 rounded-full", alt: @user.pseudo),
          destroy_user_session_path, data: {turbo_method: :delete} %>
      <% end %>
    <% end %>
    </div>
  </header>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_tip.html.erb
<div class="tip px-3">
  <div class="d-flex align-items-center gap-3">
    <i class="fa-solid fa-lightbulb fa-2x"></i>
    <div>
      <p class="mb-0"><%= tip&.content %></p>
      <small>Généré automatiquement</small>
    </div>
  </div>
</div>