config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :pages, only: :home
  resources :habits, only: [:index, :show, :new, :create, :destroy]
  resources :trackers 

  resources :challenges, only: [:index, :show] do
    member do
      post :join
    end
  end

  get "calendar", to: "calendar#index", as: :calendar_index

  resources :calendar, only: [] do
    collection do
      get :day
    end
  end

  # Routes pour les erreurs
  # Utilisation de match pour get, post, patch, delete
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

end

app/models/challenge.rb
class Challenge < ApplicationRecord
  belongs_to :user
  has_one :group, dependent: :destroy

  def creator
    user.avatar
  end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  def index
    @challenges = current_user.available_challenges
    @habit = Habit.new
    @categories = Category.all
    @habit_types = HabitType.all
    @habits = current_user.habits
    @user = current_user
    @habit.build_goal
  end

  def show
    @challenge = Challenge.find(params[:id])
    @habit = Habit.new
    @categories = Category.all
    @habit_types = HabitType.all
    @habits = current_user.habits
    @user = current_user
    @habit.build_goal
  end

  def join
    @challenge = Challenge.find(params[:id])
    @group = @challenge.group
    current_user.groups << @group
    redirect_to root_path, notice: "Challenge rejoint !"
    @user = current_user
    @user.gain_xp!(40)
  end
end

app/views/challenges/index.html.erb
<div class="container pt-4">
  <div class="header-show-challenges d-flex align-items-center justify-content-between mb-4">
    <div style="width: 40px;">
      <%= link_to root_path do %>
        <%= image_tag("icons/return_black.png", class: "icon-return")%>
      <% end %>
    </div>
    <div class="flex-grow-1 text-center">
      <h2 class="mb-0">Challenges</h2>
    </div>
    <div style="width: 40px;"></div>
  </div>
  <% @challenges.each do |challenge| %>
    <% organizer = challenge.group.users.first %>
    <%= link_to challenge_path(challenge), remote: true, class: "challenge-link" do %>
      <div class="card d-flex mb-3">
        <div class="d-flex align-items-start w-100">
          <%# Image du challenge en haut à gauche %>
          <%= image_tag challenge.image, class: "me-3 challenge-list-img", style: "height: 60px; width: auto; object-fit: cover; border-radius: 12px;" if challenge.image.present? %>
          <%# Contenu à droite %>
          <div class="challenge-content-card flex-grow-1">
            <h5><%= challenge.name %></h5>
            <p class="mb-2">Objectif : <%= challenge.objective %></p>
            <p>Durée : <%= challenge.duration %> jours</p>
            <div class="d-flex justify-content-between align-items-center w-100">
              <div class="d-flex align-items-center gap-2">
                <p class="mb-0">Par :</p>
                <%= image_tag("avatars/#{organizer.avatar}", class:"avatar-bordered w-8 h-8 rounded-full", alt: organizer.pseudo) %>
              </div>
              <%= link_to "Participer", join_challenge_path(challenge), data: { turbo_method: :post }, class: "btn btn-primary ms-2" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
<!-- Pour afficher le formulaire du create -->
<%= render 'habits/form', habit: @habit %>

app/views/challenges/show.html.erb
<div class="gradient-bg position-relative">
  <div class="container-fluid">
    <div class="container py-4">
      <div class="header-show">
        <%= link_to challenges_path do %>
          <%= image_tag("icons/return.png", class: "icon-return")%>
        <% end %>
      </div>
    </div>
  </div>
  <div class="chevauche-container ">
    <%= image_tag(@challenge.image, class: "chevauche-img")%>
  </div>
  <div class="container-fluid white-bg">
    <div class="container pb-2">
      <div class="content-center">
        <h2 class="mb-0" style="padding-top: 75px"><%= @challenge.name %></h2>
        <p class="<%= @challenge.group.users.include?(@user) ? 'mb-0 mt-1' : 'my-1' %>">
        <%= @challenge.description %>
        </p>
        <p class="d-flex align-items-center gap-2 justify-content-center <%= @challenge.group.users.include?(@user) ? 'my-3' : 'mb-4' %>">
          Organisé par :
          <% organizer = @challenge.group.users.where.not(id: current_user.id).first %>
          <%= image_tag("avatars/#{organizer.avatar}", class:"avatar-bordered w-8 h-8 rounded-full", alt: organizer.pseudo) %>
        </p>
        <% if @challenge.group.users.include?(@user) %>
        <% else %>
          <%= link_to "Participer au challenge", join_challenge_path(@challenge), data: { turbo_method: :post }, class: "btn btn-primary" %>
        <% end %>
      </div>
   <div class="card d-flex flex-column gap-2 <%= @challenge.group.users.include?(@user) ? 'mt-0' : 'mt-4' %>">
    <div class="detail-item d-flex align-items-center">
      <%= image_tag "icons/calendar.png", class: "me-3 icon-show flex-shrink-0", alt: "Calendrier" %>
      <span>
        Du
        <% if @challenge.start_date.year == @challenge.end_date.year %>
          <%= l(@challenge.start_date, format: "%d %B") %> au <%= l(@challenge.end_date, format: "%d %B %Y") %>.
        <% else %>
          <%= l(@challenge.start_date, format: "%d %B %Y") %> au <%= l(@challenge.end_date, format: "%d %B %Y") %>.
        <% end %>
      </span>
    </div>

    <div class="detail-item d-flex align-items-center">
      <%= image_tag "icons/goal.png", class: "me-3 icon-show flex-shrink-0", alt: "Objectif" %>
      <span><%= @challenge.objective %></span>
    </div>

    <div class="detail-item d-flex align-items-center mb-0 ">
      <%= image_tag "icons/trophy_black.png", class: "me-3 icon-show flex-shrink-0", alt: "Trophée" %>
      <span><%= @challenge.xp_reward %> XP</span>
    </div>
   </div>
      <div>
        <h4 class="mt-4">Liste des participants :</h3>
        <div class="px-4">
          <% @challenge.group.users.sort_by { |u| -u.xp_reward }.each do |user| %>
          <% if user == current_user %>
            <div class="d-flex p-2 participant-bg" style="display: flex; justify-content: space-between; align-items: center">
              <div>
                <div class="d-flex space-x-2" style="display: flex; justify-content: space-between; align-items: center; gap: 8px;">
                  <%= image_tag("avatars/#{user.avatar}", class:"avatar-bordered w-8 h-8 rounded-full", alt: user.pseudo) %>
                  <span><%= user.pseudo %></span>
                </div>
              </div>
              <div>
                <div class="font-semibold text-gray-700">
                  <span><%= user.xp_reward %> XP</span>
                </div>
              </div>
            </div>
          <% else %>
            <div class="d-flex p-2" style="display: flex; justify-content: space-between; align-items: center">
              <div>
                <div class="d-flex space-x-2" style="display: flex; justify-content: space-between; align-items: center; gap: 8px;">
                  <%= image_tag("avatars/#{user.avatar}", class:"avatar-bordered w-8 h-8 rounded-full", alt: user.pseudo) %>
                  <span><%= user.pseudo %></span>
                </div>
              </div>
              <div>
                <div class="font-semibold text-gray-700">
                  <span><%= user.xp_reward %> XP</span>
                </div>
              </div>
            </div>
          <% end %>
            <hr class="my-2"/>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Pour afficher le formulaire du create -->
<%= render 'habits/form', habit: @habit %>